<a href="https://colab.research.google.com/github/Dileep2896/Deep-Learning/blob/main/Artificial_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network - Churn Modelling

## Importing the libraries

In [48]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [49]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the datasets

In [50]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [51]:
X[:10]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [52]:
y[:10]

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0])

### Encoding the catergorical datasets

Label encoding the "gender" column

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [54]:
X[:10]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

One Hot Encoding the "Geography" Column

In [55]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [56]:
X[:10]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [0.0, 1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [1.0, 0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

Splitting the data into training and test sets

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [58]:
len(X_train), len(X_test), len(y_train), len(y_test)

(8000, 2000, 8000, 2000)

Feature scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
X_train[:10]

array([[-1.01460667, -0.5698444 ,  1.74309049,  0.16958176, -1.09168714,
        -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, -2.30455945,  0.91601335,
         0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, -1.19119591, -1.09168714,
        -0.94312892, -1.031415  ,  0.57993469, -0.92159124,  0.64259497,
        -1.03227043,  1.48533467],
       [-1.01460667, -0.5698444 ,  1.74309049,  0.03556578,  0.91601335,
         0.10961719,  0.00666099,  0.47312769, -0.92159124,  0.64259497,
        -1.03227043,  1.27652776],
       [-1.01460667, -0.5698444 ,  1.74309049,  2.05611444, -1.09168714,
         1.73658844,  1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,
         0.9687384 ,  0.55837842],
       [-1.01460667,  1.75486502, -0.57369368,  1.29325423, -1.09168714,
        -0.17749539, -

In [61]:
X_test[:10]

array([[-1.01460667,  1.75486502, -0.57369368, -0.55204276, -1.09168714,
        -0.36890377,  1.04473698,  0.8793029 , -0.92159124,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, -1.31490297, -1.09168714,
         0.10961719, -1.031415  ,  0.42972196, -0.92159124,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049,  0.57162971, -1.09168714,
         0.30102557,  1.04473698,  0.30858264, -0.92159124,  0.64259497,
         0.9687384 , -0.42478674],
       [ 0.98560362, -0.5698444 , -0.57369368,  1.41696129,  0.91601335,
        -0.65601634, -0.33936434,  0.57533623, -0.92159124, -1.55619021,
        -1.03227043, -0.18777657],
       [-1.01460667,  1.75486502, -0.57369368,  0.57162971,  0.91601335,
        -0.08179119,  0.00666099,  1.38961097,  0.8095029 ,  0.64259497,
         0.9687384 ,  0.61684179],
       [-1.01460667, -0.5698444 ,  1.74309049,  0.20050853, -1.09168714,
         1.73658844, -

## Part - 2 Building the ANN

### Initializing the ANN

In [62]:
ann = tf.keras.Sequential()

### Adding the input and first hidden layer

In [63]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding the second hidden layer

In [64]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding the output layer

In [65]:
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

## Part - 3 Training the ANN model

### Compiling the ANN model

In [66]:
ann.compile(optimizer=tf.keras.optimizers.Adam(),
            loss=tf.keras.losses.BinaryCrossentropy(),
            metrics=['accuracy'])

### Training the ANN model

In [67]:
ann.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7840
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4705 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4438 - accuracy: 0.8034
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4308 - accuracy: 0.8115
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4242 - accuracy: 0.8165
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4192 - accuracy: 0.8198
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4156 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4122 - accuracy: 0.8253
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4090 - accuracy: 0.8259
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4058 - accura

## Part - 5 Making the prediction and evaluating the model

Predicting on custom data

In [68]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.03668067]], dtype=float32)

### Predicting the Test set results

In [69]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])

### Creating the confusion matrics

In [70]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ascore = accuracy_score(y_test, y_pred)

In [71]:
cm

array([[1512,   83],
       [ 203,  202]])

In [72]:
ascore

0.857