<a href="https://colab.research.google.com/github/Dileep2896/Deep-Learning/blob/main/Artificial_Neural_Network_For_Regression_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel("/content/Folds5x2_pp.xlsx")
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X[:10], y[:10]

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        [  20.86,   57.32, 1010.24,   76.64],
        [  10.82,   37.5 , 1009.23,   96.62],
        [  26.27,   59.44, 1012.23,   58.77],
        [  15.89,   43.96, 1014.02,   75.24],
        [   9.48,   44.71, 1019.12,   66.43],
        [  14.64,   45.  , 1021.78,   41.25],
        [  11.74,   43.56, 1015.14,   70.72]]),
 array([463.26, 444.37, 488.56, 446.48, 473.9 , 443.67, 467.35, 478.42,
        475.98, 477.5 ]))

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
len(X_train), len(X_test), len(y_train), len(y_test)

(7654, 1914, 7654, 1914)

## Part 2 - Building the ANN

### Initializing the ANN

In [11]:
ann = tf.keras.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(6, activation="relu"))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(6, activation="relu"))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(1))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer="adam",
            loss=tf.keras.losses.mse)

### Training the ANN model on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 263686.7500
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 42282.9922
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 553.4209
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 241.7831
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 239.1076
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 236.0304
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 232.4350
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 228.2568
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 223.7256
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 218.4432
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 212.8154
Epoch 12/100
240/240 [==============================] - 0s 1ms/step -

### Predicting the results of the Test set

In [18]:
y_pred = ann.predict(X_test)

In [19]:
y_pred

array([[431.22662],
       [462.72897],
       [466.4447 ],
       ...,
       [473.28836],
       [440.7539 ],
       [459.6993 ]], dtype=float32)

In [21]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.23 431.23]
 [462.73 460.01]
 [466.44 461.14]
 ...
 [473.29 473.26]
 [440.75 438.  ]
 [459.7  463.28]]
