<a href="https://colab.research.google.com/github/Dileep2896/Deep-Learning/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

## Importing the libraries

In [35]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [36]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the datasets

In [37]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [38]:
X[:10]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [39]:
y[:5]

array([1, 0, 1, 0, 0])

### Encoding categorical data

Label encoding the "Gender" column

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
X[:10]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

OneHotEncoding the "Geography" column

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into training and test sets

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

### Feature scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## Part 2 - Building the ANN model

### Initializing the ANN

In [45]:
ANN_model = tf.keras.Sequential()

### Adding the input layer and the first hidden layer

In [46]:
ANN_model.add(tf.keras.layers.Dense(6, activation="relu"))

### Adding the second hidden layer

In [47]:
ANN_model.add(tf.keras.layers.Dense(6, activation="relu"))

### Adding the output layer

In [48]:
ANN_model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [51]:
ANN_model.compile(loss="binary_crossentropy",
                  optimizer="adam",
                  metrics=["accuracy"])

### Training the ANN model on the training sets

In [52]:
ANN_model.fit(X_train,
              y_train,
              batch_size=32,
              epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6193 - accuracy: 0.6536
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4847 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4495 - accuracy: 0.7980
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4143 - accuracy: 0.8148
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3992 - accuracy: 0.8253
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3844 - accuracy: 0.8370
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3741 - accuracy: 0.8422
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3676 - accuracy: 0.8461
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3633 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the results of a single observation

In [57]:
print(tf.argmax(ANN_model.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))))

tf.Tensor([0], shape=(1,), dtype=int64)
